from algorithm.AlgorithmBase import AlgorithmBase
from algorithm.Greedy import Greedy
from algorithm.DegreeCentrality import DegreeCentrality
from algorithm.CELF import CELF
from algorithm.RandomSelect import RandomSelect
from algorithm.SAW_ASA import SAW_ASA
from algorithm.NCVoteRank import NCVoteRank
from algorithm.PageRank import PageRank
from algorithm.DegreeDiscount import DegreeDiscount